MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  command: skulleater
  aliases: [cranio, cranios, devorador]
  save-interval: 600 # segundos

Messages:
  invalid-amount: '&6&lVoltz&f&lMC &8&l➜ &cA quantia informada é inválida!'
  insufficient-skulls: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui crânios suficientes! ({has}/{need})'
  need-space: '&6&lVoltz&f&lMC &8&l➜ &cVocê não possui espaço suficiente no seu inventário! ({has}/{need})'
  pvp-area: '&6&lVoltz&f&lMC &8&l➜ &cVocê não pode ativar esse item em uma área de PvP!'
  choose-amount:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Digite no chat quantos itens deseja comprar!'
    - ''
    - ' &8▶ &7Comprando: &f{item}'
    - ' &8▶ &7Preço: &f{price} &4&l۞'
    - ''
  successful-purchased:
    - ''
    - '&6&lVoltz&f&lMC &8&l➜ &7Compra efetuada com sucesso!'
    - ''
    - ' &8▶ &7Item adquirido: &f{item}'
    - ' &8▶ &7Quantia: &fx{amount}'
    - ' &8▶ &7Preço: &f{price} &4&l۞'
    - ''

Titles:
  item-activated:
    title: ''
    subtitle: '&4+{amount} &l۞'

Next-Page:
  type: ARROW
  name: '&aPróxima Página'

Previous-Page:
  type: ARROW
  name: '&cPágina Anterior'

Item:
  type: SKULL_ITEM
  owner: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTZiYmZkNWJlZjAyMzllZmFjYmM5YWVjMjRjNTBjMzAzOTQzYTM0OGY4MmJkYzVhZTkyYjFlNmQ2MDFjZjNlZCJ9fX0=
  name: '&4Crânio &7(Botão direito)'
  lore:
    - '&7Ofereça esse crânio ao &fDevorador'
    - '&fde Crânios &7e ganhe em troca muitos'
    - '&7itens poderosos!'